id: P25645A61
initial_creation_type: input
source_metadata:
  title: Gesar Series
  language: bo
  description: 'A series of texts dedicated to the legendary warrior king Gesar (ge
    sar):'
  volume:
    a6dfba9801864b6da94fc7dc71630a43:
      title: Concerning Offering Rites to the Great Lion Gesar
      parent: Commentaries
    633e66b6b0c844eb8e995b2eebc0ceed:
      title: 'The Swift Infusion of Blessings: A Guru Yoga of the Great Embodiment
        of Unchanging Awareness Wisdom'
      parent: Guru Yoga
    bc2408d51a2e4eb7af5ebff9bb91eb0b:
      title: Brief Gesar Windhorse Invocation
      parent: Lungta
    37c345bb814c45c09e3ddc102ca0bb93:
      title: Short Windhorse Prayer to Gesar
      parent: Lungta
    9a59fc32d86945d4b360f10776d4b26b:
      title: The Swift Accomplishment of Enlightened Activity through Invocation and
        Offering
      parent: Offering Rites
    10c4f9334ffd4796aef723784d9f71d3:
      title: Petitionary Offering to Norbu Dradül Tsal
      parent: Prayers
    a5c2f889aa8e427da56f573d64e2e524:
      title: Brief Offering Prayer to Gesar
      parent: Prayers
    a6b3e99351a44175a38c35d46ca61a1c:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Prayers
    d3245d06bbc3419d9d6d7722c776914a:
      title: Prayer to Gesar
      parent: Prayers
    e41fced907b94c19bc9ac87619d8fedd:
      title: The Prayer and Offering to 'The Great Lion, Gesar the Jewel', that Spontaneously
        Accomplishes Activities
      parent: Prayers
    acee681fac2444eeaaf01d40c0cbf0fc:
      title: 'The Spontaneous Fulfilment of Wishes: A Daily Prayer to Gesar, King
        of the Dralas'
      parent: Prayers
    aaf2256adf7444e7b10e05e6a19ac6a5:
      title: 'The Swift Fulfilment of Wishes: A Brief Offering Prayer to King Gesar'
      parent: Prayers
    98cd53b6a930447ab23b6eab03dcb05c:
      title: Brief Smoke Offering to the Great Lion of the World
      parent: Sang Offering
created_at: '2022-03-01T03:43:17.456326'
last_modified_at: '2022-03-01T03:43:17.456329'
statistics:
  total_words: 6689
  total_non_words: 623
quality:
  non_words_ratio: 0.09
